apiVersion: addons.cluster.x-k8s.io/v1alpha4
kind: ClusterResourceSet
metadata:
  labels:
    konvoy.d2iq.io/cluster-name: {{ .Release.Name }}
  name: ccm-cpi-config-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterSelector:
    matchLabels:
      konvoy.d2iq.io/cluster-name: {{ .Release.Name }}
  resources:
  - kind: ConfigMap
    name: capvcd-cm-{{ .Release.Name }}
  - kind: Secret
    name: capvcd-secret-{{ .Release.Name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: capvcd-secret-{{ .Release.Name }}
type: addons.cluster.x-k8s.io/resource-set
stringData:
  capvcd-secret.yaml: |-
    ---
    apiVersion: v1
    stringData:
      clusterid: NO_RDE_{{ .Values.vcd.org_vdc }}-{{ .Release.Name }} 
    kind: Secret
    metadata:
      name: vcloud-clusterid-secret
      namespace: kube-system
    ---
    apiVersion: v1
    data:
      refreshToken: {{ .Values.cluster.refresh_token_b64 }}
      password: {{ .Values.cluster.password }}
      username: {{ .Values.cluster.username }}
    kind: Secret
    metadata:
      name: vcloud-basic-auth
      namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: capvcd-cm-{{ .Release.Name }}
data:
  capvcd-config.yaml: |-
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: vcloud-ccm-configmap
      namespace: kube-system
    data:
      vcloud-ccm-config.yaml: |+
        vcd:
          host: {{ .Values.vcd.site }}
          org: {{ .Values.vcd.org }}
          vdc: {{ .Values.vcd.org_vdc }}
        clusterid: NO_RDE_{{ .Values.vcd.org_vdc }}-{{ .Release.Name }}
        vAppName: {{ .Release.Name }}
        loadbalancer:
          network: {{ .Values.vcd.org_vdc_network }}
          enableVirtualServiceSharedIP: true
          oneArm:
            startIP: "10.20.0.8"
            endIP: "10.20.0.9"
          ports:
            http: 80
            https: 443
    immutable: true
