apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Release.Name }}
  labels:
    cni: {{ .Values.cluster.cni }}
    ccm: {{ .Values.cluster.ccm }}
    csi: {{ .Values.cluster.csi }}
    konvoy.d2iq.io/cluster-name: {{ .Release.Name }}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - {{ .Values.cluster.cidr.pod }}
    serviceDomain: cluster.local
    services:
      cidrBlocks:
        - {{ .Values.cluster.cidr.service }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: {{ .Release.Name }}-control-plane
    namespace: {{ .Release.Namespace }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: VCDCluster
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }} 
