---
apiVersion: v1
data:
  value: {{ .Values.cluster.encryptionConfigValueB64 }}
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ .Values.cluster.name }}
    clusterctl.cluster.x-k8s.io/move: ""
  name: {{ .Values.cluster.name }}-etcd-encryption-config
  namespace: {{ .Release.Namespace }}
type: Opaque
