{{- $releaseName := .Release.Name  }}
{{- $releaseNamespace := .Release.Namespace }}
{{- $cluster := .Values.cluster }}
{{- range $key, $workerNodePool := .Values.workerNodePools }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ $releaseName }}-{{ $workerNodePool.poolName }}
  namespace: {{ $releaseNamespace }}
spec:
  clusterName: {{ $releaseName }}
  replicas: {{ $workerNodePool.replicas }} 
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ $releaseName }}-{{ $workerNodePool.poolName }}
          namespace: {{ $releaseNamespace }}
      clusterName: {{ $releaseName }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: VCDMachineTemplate
        name: {{ $releaseName }}-{{ $workerNodePool.poolName }}-{{ $cluster.kubernetesVersion }}
        namespace: {{ $releaseNamespace }}
      version: {{ $cluster.kubernetesVersion }}
{{- end }} 
