---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ .Values.cluster.name }}-wp1
  namespace: {{ .Release.Namespace }}
spec:
  clusterName: {{ .Values.cluster.name }}
  replicas: {{ .Values.cluster.workerNodes.replicas}} 
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ .Values.cluster.name }}-wp1
          namespace: {{ .Release.Namespace }}
      clusterName: {{ .Values.cluster.name }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: VCDMachineTemplate
        name: {{ .Values.cluster.name }}-wp1-{{ .Values.cluster.kubernetesVersion }}
        namespace: {{ .Release.Namespace }}
      version: {{ .Values.cluster.kubernetesVersion }} 
