apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VCDCluster
metadata:
  name: {{ .Release.Name }}
spec:
  site: {{ .Values.vcd.site }}
  org:  {{ .Values.vcd.org }}
  ovdc: {{ .Values.vcd.org_vdc }}
  ovdcNetwork: {{ .Values.vcd.org_vdc_network }}
  useAsManagementCluster: {{ .Values.cluster.isManagement }}
  userContext:
    secretRef:
      name: {{ .Values.cluster.capv_credentials_secret }}
      namespace: {{ .Release.Namespace }}
  rdeId: NO_RDE_{{ .Values.vcd.org_vdc }}-{{ .Release.Name }}
  controlPlaneEndpoint:
    host: {{ .Values.cluster.external_vip | default .Values.controlplane.vip_ip }}
    port: 6443
  #loadBalancerConfigSpec:
   # useOneArm: ${USE_ONE_ARM}
   # vipSubnet: ${VCD_VIP_CIDR} # Virtual IP CIDR for the external network
  proxyConfigSpec:
    httpProxy: {{ .Values.cluster.http_proxy }}
    httpsProxy: {{ .Values.cluster.https_proxy }}
    noProxy: {{ .Values.cluster.no_proxy }}
