apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VCDMachineTemplate
metadata:
  name: {{ .Values.cluster.name }}-control-plane
spec:
  template:
    spec:
      catalog: {{ .Values.controlPlaneMachineTemplate.catalog }} # Catalog hosting the TKGm template, which will be used to deploy the control plane VMs
      template: {{ .Values.controlPlaneMachineTemplate.catalog.template }} # Name of the template to be used to create (or) upgrade the control plane nodes
      sizingPolicy: {{ .Values.controlPlaneMachineTemplate.sizingPolicy }} # Sizing policy to be used for the control plane VMs (this must be pre-published on the chosen organization virtual datacenter)
      placementPolicy: {{ .Values.controlPlaneMachineTemplate.placementPolicy }} # Placement policy to be used for worker VMs (this must be pre-published on the chosen organization virtual datacenter)
      storageProfile: {{ .Values.controlPlaneMachineTemplate.storageProfile }} # Storage profile to be used for the control plane VMs (this must be pre-published on the chosen organization virtual datacenter)
      enableNvidiaGPU: {{ .Values.controlPlaneMachineTemplate.enableNvidiaGPU }}
