{{- if .Values.cluster.lastKubernetesVersion }}{{ if .Values.cluster.lastvCDTemplate }}
{{- $releaseName := .Release.Name  }}
{{- $cluster := .Values.cluster }}
{{- range $key, $workerNodePool := .Values.workerNodePools }}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VCDMachineTemplate
metadata:
  name: {{ $releaseName }}-{{ $workerNodePool.poolName }}-{{ $cluster.lastkubernetesVersion }}
spec:
  template:
    spec:
      {{- if $workerNodePool.workerNodesMachineTemplate.catalog }}
      catalog: {{ $workerNodePool.workerNodesMachineTemplate.catalog }}
      {{- else }}
      catalog: {{ $cluster.catalog }}
      {{- end }}
      {{- if $workerNodePool.workerNodesMachineTemplate.lastvAppTemplate }}
      template: {{ $workerNodePool.workerNodesMachineTemplate.lastvAppTemplate }}
      {{- else }}
      template: {{ $cluster.lastvAppTemplate }}
      {{- end }}
      sizingPolicy: {{ $workerNodePool.workerNodesMachineTemplate.sizingPolicy }}
      placementPolicy: {{ $workerNodePool.workerNodesMachineTemplate.placementPolicy }}
      storageProfile: {{ $workerNodePool.workerNodesMachineTemplate.storageProfile }}
      enableNvidiaGPU: {{ $workerNodePool.workerNodesMachineTemplate.enableNvidiaGPU }}
{{- end }}
{{- end }}{{ end }}
