apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VCDMachineTemplate
metadata:
  name: {{ .Values.cluster.name }}-control-plane
spec:
  template:
    spec:
      catalog: {{ .Values.controlPlaneMachineTemplate.catalog }}
      template: {{ .Values.controlPlaneMachineTemplate.vAppTemplate }}
      sizingPolicy: {{ .Values.controlPlaneMachineTemplate.sizingPolicy }}
      placementPolicy: {{ .Values.controlPlaneMachineTemplate.placementPolicy }}
      storageProfile: {{ .Values.controlPlaneMachineTemplate.storageProfile }}
      enableNvidiaGPU: {{ .Values.controlPlaneMachineTemplate.enableNvidiaGPU }}
