apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VCDMachineTemplate
metadata:
  name: {{ .Values.cluster.name }}-worker-pool-1
spec:
  template:
    spec:
      catalog: {{ .Values.cluster.catalog }}
      template: {{ .Values.cluster.vAppTemplate }}
      sizingPolicy: {{ .Values.workerNodesMachineTemplate.sizingPolicy }}
      placementPolicy: {{ .Values.workerNodesMachineTemplate.placementPolicy }}
      storageProfile: {{ .Values.workerNodesMachineTemplate.storageProfile }}
      enableNvidiaGPU: {{ .Values.workerNodesMachineTemplate.enableNvidiaGPU }}
