apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VCDCluster
metadata:
  name: {{ .Values.cluster.name }}
spec:
  site: {{ .Values.vcd.site }} # VCD endpoint with the format https://VCD_HOST. No trailing '/'
  org:  {{ .Values.vcd.org }}# VCD organization name where the cluster should be deployed
  ovdc: {{ .Values.vcd.org_vdc }} # VCD virtual datacenter name where the cluster should be deployed
  ovdcNetwork: {{ .Values.vcd.org_vdc_network }} # VCD virtual datacenter network to be used by the cluster
  useAsManagementCluster: {{ .Values.cluster.isManagement }} # intent to use the resultant CAPVCD cluster as a management cluster
  userContext:
    secretRef:
      name: capi-user-credentials-{{ .Values.cluster.name }} # name of the secret containing the credentials of the VCD persona creating the cluster
      namespace: {{ .Release.Namespace }} # name of the secret containing the credentials of the VCD persona creating the cluster
  rdeId: NO_RDE-{{ .Values.vcd.org_vdc }}-{{ .Values.cluster.name }} # rdeId if it is already created. If empty, CAPVCD will create one for the cluster.
  controlPlaneEndpoint:
    host: {{ .Values.cluster.controlplane.vip_ip }}
    port: 6443
  #loadBalancerConfigSpec:
   # useOneArm: ${USE_ONE_ARM}
   # vipSubnet: ${VCD_VIP_CIDR} # Virtual IP CIDR for the external network
  proxyConfigSpec:
    httpProxy: {{ .Values.cluster.http_proxy }}
    httpsProxy: {{ .Values.cluster.https_proxy }}
    noProxy: {{ .Values.cluster.no_proxy }}
