apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VCDMachineTemplate
metadata:
  name: {{ .Release.Name }}-cp-{{ .Values.cluster.kubernetesVersion }}
spec:
  template:
    spec:
      {{- if .Values.controlplane.controlPlaneMachineTemplate.catalog }}
      catalog: {{ .Values.controlplane.controlPlaneMachineTemplate.catalog }}
      {{- else }}
      catalog: {{ .Values.cluster.catalog }}
      {{- end }}
      {{- if .Values.controlplane.controlPlaneMachineTemplate.vAppTemplate }}
      template: {{ .Values.controlplane.controlPlaneMachineTemplate.vAppTemplate }}
      {{- else }}
      template: {{ .Values.cluster.vAppTemplate }}
      {{- end }}
      sizingPolicy: {{ .Values.controlplane.controlPlaneMachineTemplate.sizingPolicy }}
      placementPolicy: {{ .Values.controlplane.controlPlaneMachineTemplate.placementPolicy }}
      storageProfile: {{ .Values.controlplane.controlPlaneMachineTemplate.storageProfile }}
      enableNvidiaGPU: {{ .Values.controlplane.controlPlaneMachineTemplate.enableNvidiaGPU }}
