{{- if .Values.cluster.lastKubernetesVersion }}{{ if .Values.cluster.lastvCDTemplate }}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VCDMachineTemplate
metadata:
  name: {{ .Values.cluster.name }}-wp1-{{ .Values.cluster.lastKubernetesVersion }}
spec:
  template:
    spec:
      catalog: {{ .Values.cluster.catalog }}
      template: {{ .Values.cluster.lastvCDTemplate }}
      sizingPolicy: {{ .Values.workerNodesMachineTemplate.sizingPolicy }}
      placementPolicy: {{ .Values.workerNodesMachineTemplate.placementPolicy }}
      storageProfile: {{ .Values.workerNodesMachineTemplate.storageProfile }}
      enableNvidiaGPU: {{ .Values.workerNodesMachineTemplate.enableNvidiaGPU }}
{{- end }}{{ end }}
